### ISSUE TITLE
Client-generated and server-generated time indicators aren't identical.

### ISSUE THREAD

**Issue by jorams** [Shinmera/autobuild#10]
This is a small stylistic issue:

On any page that displays text like "1 hour 22 minutes 15 seconds", after the next automatic refresh the client-side Javascript will add an "s" to the end of "hour", because it doesn't have anything like the `~:p` used to `FORMAT` the values server-side.

**Comment by Shinmera** [comment]
Yeah that's been a thing I noticed for a while. I've been too lazy to fix it.
