### ISSUE TITLE
Non-canonical build folder names

### ISSUE THREAD

**Issue by Georgiy-Tugai** [Shinmera/autobuild#11]
The build folder name depends on the method used to create a build.
If I enter a tag (`0.4.0`) or ref (`HEAD`) instead of a commit hash, or a shortened commit hash, into the "manual build creation" box, the build is successfully created, but the folder name is based on what was entered into the box, rather than the full commit hash as when a build is automatically created.
This is doubly confusing since the build-view does not show the alternate name instead of the commit hash.

I believe that build folders (`projects/project/.autobuild/foo`) should be created using a canonical representation; whether that is the full commit hash, a shortened commit hash or the output of `git describe --long`.

**Comment by Shinmera** [comment]
Ah, good catch. Yeah that should definitely be fixed.
