### ISSUE TITLE
Stopping a scheduled build (seems to) do nothing

### ISSUE THREAD

**Issue by Georgiy-Tugai** [Shinmera/autobuild#13]
Steps to reproduce:
1. start a build (to ensure that the following build is `scheduled` rather than run immediately)
2. create another build of any project
3. start the build, which ends up in `scheduled` state
4. stop the build, state remains `scheduled`
5. delete the build
6. re-create the build, a notification appears about the build entering `created` state -- this seems to imply that the build was never completely destroyed. This part may be a UI-only issue.

I have not tested whether the re-created build runs of it's own volition when the other build completes.

**Comment by Shinmera** [comment]
This is a known problem with simple-tasks. The fix is non-trivial due to threading, but I'll see if I can come up with a solution that isn't completely gross.
