### ISSUE TITLE
Incorrect notifications after every page load

### ISSUE THREAD

**Issue by jorams** [Shinmera/autobuild#17]
When I open an Autobuild page and then wait for the first automatic update, a notification is shown for every build on that page. On the homepage that means a _ton_ of notifications are shown. All statuses are shown as having changed, even though none have _actually_ changed.

This happens in both Firefox 42.0 and Chromium 46.0.2490.80, so it's not browser-specific.

I think this is a regression, as the previous version of Autobuild I used (from 1 November) did not have the issue.

**Comment by Shinmera** [comment]
I cannot reproduce this when I simply open a page in the browser. However, it _does_ happen if I close and re-open the browser entirely. I have no idea why the hell that would happen, there must be some weird caching mechanism in the browser that I am not aware of.
