### ISSUE TITLE
Should Poll for New Projects and Builds

### ISSUE THREAD

**Issue by Shinmera** [Shinmera/autobuild#5]
Currently it only polls status updates. It'd be useful if it could poll for new builds and projects as well and update the UI accordingly. Some more sophisticated internal representation of the objects on the JS side would probably be handy to facilitate that -- mostly also a serialisation method and such.

**Comment by jorams** [comment]
A simple start for this could be to automatically reload the page when a new project or build is available. Implementing that should be significantly simpler than fully client-side UI updates, while providing most of the value.

**Comment by Shinmera** [comment]
Refreshing is not a plausible choice of action as it might happen while the user is doing something, potentially leading to lost sate.
