### ISSUE TITLE
Search/replace feature kills files

### ISSUE THREAD

**Issue by Georgiy-Tugai** [Shinmera/autobuild#9]
Given that `the/file` is a shell script in the project directory, starting with `#! /bin/bash`, the Autobuild recipe `(:build (s/r "the/file" "#! /bin/bash" "#!/usr/bin/env"))` results in that file becoming empty.

**Comment by Shinmera** [comment]
Ergh. The problem is that I'm trying to make things neat and tidy by using `(with-open-file (.. :direction :io :if-exists :supersede) ..)` but that clears the file before it is read on SBCL. I'll fix it asap.
